
spring.application.name=eventify

#Conexion a la base de datos postgresSQL real

spring.datasource.url=jdbc:postgresql://localhost:5433/postgres
spring.datasource.username=postgres
spring.datasource.password=eventify123
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración adicional recomendada para JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none




